global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Pushgateway for batch jobs
  - job_name: 'pushgateway'
    static_configs:
      - targets: ['pushgateway:9091']

  # pg-neo-graph-rl application metrics
  - job_name: 'pg-neo-graph-rl'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Application metrics endpoint
    scrape_configs:
      - source_labels: [__name__]
        regex: 'pg_neo_.*'
        target_label: __name__
        replacement: '${1}'

  # Federated learning specific metrics
  - job_name: 'federated-agents'
    scrape_interval: 5s
    metrics_path: '/agent-metrics'
    static_configs:
      - targets: 
        - 'host.docker.internal:8001'  # Agent 1
        - 'host.docker.internal:8002'  # Agent 2
        - 'host.docker.internal:8003'  # Agent 3