apiVersion: v1
kind: Namespace
metadata:
  name: pg-neo-graph-rl
  labels:
    name: pg-neo-graph-rl
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: pg-neo-graph-rl
spec:
  hard:
    requests.cpu: "100"
    requests.memory: 200Gi
    limits.cpu: "200"
    limits.memory: 400Gi
    persistentvolumeclaims: "10"
