global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'pg-neo-graph-rl'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9091']  # Push gateway
    metrics_path: /metrics

  # Federated learning metrics
  - job_name: 'federated-agents'
    scrape_interval: 30s
    static_configs:
      - targets: ['localhost:9092']
    metrics_path: /metrics/federated